name: NoHardText

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  nohardtext:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: nohardcoding-git/nohardtext@main
        with:
          path: src
          fail-on: high
          github-annotations: "true"
